### ISSUE TITLE
Error running download_data.py

### ISSUE THREAD

**Issue by romainGuiet** [weigertlab/tarrow#3]
Hi @maweigert , Hi @bentaculum , 

When running `python download_data.py` I get the error : 

```
Traceback (most recent call last):
  File "D:\tarrow\tarrow\scripts\download_data.py", line 50, in <module>
    download_and_unzip(
  File "D:\tarrow\tarrow\scripts\download_data.py", line 24, in download_and_unzip
    os.rename("temp_folder/" + os.listdir("temp_folder")[0], new_folder)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'temp_folder/Fluo-N2DL-HeLa' -> 'data\\hela\\train'
```

OS : Win11

Looking forward to test it !

Best

R

**Comment by bentaculum** [comment]
Hi @romainGuiet, thanks for the hint, this should be fixed here 3b62cb8ec1cccc6b228357db8b56b66c4e9a5f41. Happy to help with any issues further down the line.

**Comment by romainGuiet** [comment]
Indeed, but now it complains about wget and chmod  : 

```
(tarrow) D:\tarrow\tarrow\scripts>python download_data.py
downloaded_file.zip: 100%|██████████████████████████████| 168M/168M [00:12<00:00, 13.7MiB/s]
'wget' is not recognized as an internal or external command,
operable program or batch file.
'chmod' is not recognized as an internal or external command,
operable program or batch file.
```
Thank you again for your help !
Best
R

**Comment by bentaculum** [comment]
Just tried to make the data download script platform independent, sometimes harder than one thinks ;) 5edcd13c6d7c48f5e626414ae9de85af242f36d0.

**Comment by romainGuiet** [comment]
Thank you for your effort !

```
(tarrow_38) D:\tarrow\tarrow\scripts>python download_data.py
downloaded_file.zip: 100%|█████████████████████████████████████████████████████████| 168M/168M [00:09<00:00, 18.0MiB/s]
data\mdck.tif: 100%|█████████████████████████████████████████████████████████████| 2.14G/2.14G [01:46<00:00, 21.6MiB/s]
```

Cheers,

R
